spring:
  profiles:
    active: dev
  application:
    name: ttcs
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE-CLIENT-ID}
            client-secret: ${GOOGLE-CLIENT-SECRET}
            redirect-uri: ${fe_base_url}/oauth/redirect?provider=google
          github:
            client-id: ${GITHUB-CLIENT-ID}
            client-secret: ${GITHUB-CLIENT-SECRET}
            redirect-uri: ${fe_base_url}/oauth/redirect?provider=github
            scope:
              - user:email
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080,http://localhost:5173